telegram_accounts:
  - "user_id_1"
  - "user_id_2"
  - "user_id_3"

twitter_accounts:
  - username: "your_twitter_username_1"
    consumer_key: "your_consumer_key_1"
    consumer_secret: "your_consumer_secret_1"
    access_token: "your_access_token_1"
    access_token_secret: "your_access_token_secret_1"

  - username: "your_twitter_username_2"
    consumer_key: "your_consumer_key_2"
    consumer_secret: "your_consumer_secret_2"
    access_token: "your_access_token_2"
    access_token_secret: "your_access_token_secret_2"

logging:
  level: "INFO"
  file: "logs/app.log"
